base/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings
from my_apps.recipes_app.views import *

urlpatterns = [
    path('admin/', admin.site.urls),

    # ckeditor for admin-page
    path('ckeditor/', include('ckeditor_uploader.urls')),

    # recipes_app urls
    path('', include('my_apps.recipes_app.urls')),

    # users_app urls
    path('users/authenticate/', include('django.contrib.auth.urls')),
    path('users/authenticate/', include('my_apps.users_app.urls')),
    
    # cookies page
    path('cookies/', cookies, name='cookies'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# image
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_apps/recipes_app/urls.py
from django.urls import path
from . import views

from django.conf.urls.static import static
from django.conf import settings
from my_apps.recipes_app.views import *

urlpatterns = [
    # path('', views.HomeView.as_view(), name='home'),

    path('', main_page, name='index'),
    path('<int:recipe_id>', single_recipe, name='single_recipe'),
    path('soup', soup_page, name='soup_page'),
    path('dish', dish_page, name='dish_page'),
    path('aperetize', aperetize_page, name='aperetize_page'),
    path('drink', drink_page, name='drink_page'),
    path('rewiew/<int:pk>', add_comments, name='add_comments'),
    path('search', search_page, name='search_page'),
]

my_apps/users_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('authenticate/login_user', views.login_user, name="login"),
    path('authenticate/logout_user', views.logout_user, name="logout"),
    path('authenticate/register_user', views.register_user, name="register_user")
]

my_apps/recipes_app/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField


# Create your models here.
class Recipes(models.Model):
    name = models.CharField('Назва страв', max_length=30, blank=True)
    food_type = models.CharField('Тип їжі', max_length=20, blank=True, default='')
    short_desc = models.TextField('Короткий опис', max_length=80, blank=True)
    img = models.ImageField(upload_to="media/", verbose_name='img', blank=True, null=True)
    text = RichTextUploadingField('Recipe', blank=True)

    def __str__(self):
        return self.name


class Comments(models.Model):
    name = models.CharField("Ім'я", max_length=50)
    text_comments = models.TextField("Текст комментаря", max_length=2000)
    recipe = models.ForeignKey(Recipes, verbose_name='Post', on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.name}, {self.text_comments}, {self.date_added}, {self.recipe}'

my_apps/users_app/models.py
from django.db import models

# Create your models here.

my_apps/users_app/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class RegisterUserForm(UserCreationForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(max_length=50, label="Ім'я", widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=70, label='Фамілія', widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')


    def __init__(self, *args, **kwargs):
        super(RegisterUserForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'

my_apps/recipes_app/views.py
from django.shortcuts import render, redirect
from my_apps.recipes_app.models import Recipes
from my_apps.recipes_app.models import Comments
from .form import CommentsForm

# Create your views here.

def main_page(request):
    recipes = Recipes.objects.all()
    return render(request, 'index.html', {'recipes': recipes})


def single_recipe(request, recipe_id):
    recipe = Recipes.objects.get(pk=recipe_id)
    return render(request, 'single_recipe.html', context={'recipe': recipe})


def soup_page(request):
    soup = Recipes.objects.filter(food_type="soup")
    return render(request, 'soup_page.html', context={'soup': soup})
    

def dish_page(request):
    dish = Recipes.objects.filter(food_type='dish')
    return render(request, 'dish_page.html', context={'dish': dish})


def aperetize_page(request):
    aperetize = Recipes.objects.filter(food_type='aperetize')
    return render(request, 'aperetize_page.html', context={'aperetize': aperetize})


def drink_page(request):
    drink = Recipes.objects.filter(food_type='drink')
    return render(request, 'drink_page.html', context={'drink': drink})

def search_page(request):
    if request.method == 'POST':
        searched = request.POST['searched']
        recipes = Recipes.objects.filter(name__contains=searched.upper())
        return render(request, 'search_page.html', {'searched': searched.upper(), 'recipes': recipes})
    else:
        return render(request, 'search_page.html', {})

def add_comments(request, pk):
    form = CommentsForm(request.POST)
    if form.is_valid():
        form = form.save(commit=False)
        form.recipe_id = pk
        form.save()
    return redirect(f'/{pk}')

def cookies(request):
    return render(request, 'cookies.html')

my_apps/users_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from .forms import RegisterUserForm


# Create your views here.
def login_user(request):
    if request.method == 'POST':
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('index')
            # Redirect to a success page.
            
        else:
            # Return an 'invalid login' error message.
            messages.success(request, ("Помилка! Ви ввели не корректний пароль або логін! Спробуйте ще..."))
            return redirect('login')


    else:
        return render(request,'authenticate/login.html', {})

def logout_user(request):
    logout(request)
    messages.success(request, ("Ви вийшли з облікового запису"))
    return redirect('index')

def register_user(request):
    if request.method == 'POST':
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            messages.success(request, ("Реєстрація успішна!"))
            return redirect('index')
    else:
        form = RegisterUserForm()

    return render(request, 'authenticate/register_user.html', {'form': form,})

recipes_app/views.py
from django.shortcuts import render, redirect
from recipes_app.models import Recipes
from recipes_app.models import Comments
from .form import CommentsForm

# Create your views here.

def main_page(request):
    recipes = Recipes.objects.all()
    return render(request, 'index.html', {'recipes': recipes})


def single_recipe(request, recipe_id):
    recipe = Recipes.objects.get(pk=recipe_id)
    return render(request, 'single_recipe.html', context={'recipe': recipe})


def soup_page(request):
    soup = Recipes.objects.filter(food_type="soup")
    return render(request, 'soup_page.html', context={'soup': soup})
    

def dish_page(request):
    dish = Recipes.objects.filter(food_type='dish')
    return render(request, 'dish_page.html', context={'dish': dish})


def aperetize_page(request):
    aperetize = Recipes.objects.filter(food_type='aperetize')
    return render(request, 'aperetize_page.html', context={'aperetize': aperetize})


def drink_page(request):
    drink = Recipes.objects.filter(food_type='drink')
    return render(request, 'drink_page.html', context={'drink': drink})


def add_comments(request, pk):
    form = CommentsForm(request.POST)
    if form.is_valid():
        form = form.save(commit=False)
        form.recipe_id = pk
        form.save()
    return redirect(f'/{pk}')

def cookies(request):
    return render(request, 'cookies.html')

my_apps/recipes_app/templates/aperetize_page.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div class="recipe-item">
    <div class="container shadow p-4 mb-5 mt-5 bg-body rounded">
        <h1>Закуски </h1>

        <div class="row gy-3">
            {%  for i in aperetize %}
            <div class="col-lg-3 col-md-4 col-sm-6 col-6">
                <div class="card h-100 mb-3">
                    <a href="{{i.id}}"><img src="{{i.img.url}}" class="card-img-top" alt="..."></a>
                    <div class="card-body">
                    <a href="{{i.id}}">
                        <h5 class="card-title">{{i.name}}</h5>
                    </a>                     
                    <p class="card-text">{{i.short_desc}}</p>
                    </div>
                </div> 
            </div>        
            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}

my_apps/recipes_app/templates/dish_page.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div class="recipe-item">
    <div class="container shadow p-4 mb-5 mt-5 bg-body rounded">
        <h1>Другі страви </h1>

        <div class="row gy-3">
            {% for i in dish %}
            <div class="col-lg-3 col-md-4 col-sm-6 col-6">
                <div class="card h-100 mb-3">
                    <a href="{{i.id}}"><img src="{{i.img.url}}" class="card-img-top" alt="..."></a>
                    <div class="card-body">
                    <a href="{{i.id}}">
                        <h5 class="card-title">{{i.name}}</h5>
                    </a>                     
                    <p class="card-text">{{i.short_desc}}</p>
                    </div>
                </div> 
            </div>             
            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}

my_apps/recipes_app/templates/drink_page.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div class="container shadow p-4 mb-5 mt-5 bg-body rounded">
    <div class="container">
        <h1>Напої </h1>

        <div class="row gy-3">
            {%  for i in drink %}
            <div class="col-lg-3 col-md-4 col-sm-6 col-6">
                <div class="card h-100 mb-3">
                    <a href="{{i.id}}"><img src="{{i.img.url}}" class="card-img-top" alt="..."></a>
                    <div class="card-body">
                    <a href="{{i.id}}">
                        <h5 class="card-title">{{i.name}}</h5>
                    </a>                     
                    <p class="card-text">{{i.short_desc}}</p>
                    </div>
                </div> 
            </div>     
            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}

my_apps/recipes_app/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="container shadow p-4 mb-5 mt-3 bg-body rounded">
    <div class="banner p-4 p-md-3 mb-4 rounded text-body-emphasis">
      <div class="col-lg-12 px-0">
        <img src="{% static 'img/008.png' %}" class="img" alt="...">
        <h1 class="main-title display-4 fw-bolder">Файні рецепти</h1>
        <p class="lead my-3 text-center">Тільки перевірені рецепти домашньої кухні Закарпаття </p>
      </div>
    </div>
</div>

<div class="recipe-item">
    <div class="container shadow p-4 mb-5 mt-5 bg-body rounded">
        <h1>Рецепти</h1>
        <div class="row gy-3">
            {%  for i in recipes %}
            <div class="col-lg-3 col-md-4 col-sm-6 col-6">
                <div class="card h-100 mb-3">
                    <a href="{{i.id}}"><img src="{{i.img.url}}" class="card-img-top" alt="..."></a>
                    <div class="card-body">
                        <a href="{{i.id}}">
                            <h5 class="card-title">{{i.name}}</h5>
                        </a>
                        {% comment %} <h5 class="card-title">{{i.name}}</h5> {% endcomment %}
                        <p class="card-text">{{i.short_desc}}</p>
                        {% comment %} <a href="{{i.id}}">більше...</a> {% endcomment %}
                    </div>
                </div> 
            </div>
            {% endfor %}
            
        </div>
    </div>
</div>
{% endblock content %}

my_apps/recipes_app/templates/search_page.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div class="recipe-item">
    <div class="container shadow p-4 mb-5 mt-5 bg-body rounded">
        {% if searched %}
        <h1>Результат пошуку "{{ searched }}"</h1>

        <div class="row gy-3">
            {% for i in recipes %}
            <div class="col-lg-3 col-md-4 col-sm-6 col-6">
                <div class="card h-100 mb-3">
                    <a href="{{i.id}}"><img src="{{i.img.url}}" class="card-img-top" alt="..."></a>
                    <div class="card-body">
                    <a href="{{i.id}}">
                        <h5 class="card-title">{{i.name}}</h5>
                    </a>                     
                    <p class="card-text">{{i.short_desc}}</p>
                    </div>
                </div> 
            </div>             
            {% endfor %}
        </div>
        {% else %}
        <h1>Нічого не знайдено ...{{ searched }}</h1>
        {% endif %}

    </div>
</div>

{% endblock content %}

my_apps/recipes_app/templates/single_recipe.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="recipe-page">
    <div class="container shadow p-4 mb-5 mt-5 bg-body rounded">
        <h1>{{recipe.name}}</h1>
            <div class="recipe-img">
                {% comment %} <img src="./www.pythonanywhere.com_user_ludvigdodi_files_home_ludvigdodi_food_page_templates_single_recipe_files/{{recipe.img.url}}" class="rounded" width="400" height="400" alt="голубці"> {% endcomment %}
            </div>
            <div class="recipe-content">
                <p class="ck-content">{{recipe.text | safe}}</p>
                <!--<p>{{recipe.text_second|safe}}</p>-->
            </div>
    </div>
</div>

<div class="comments">
    {% if user.is_authenticated %}
    <div class="container shadow p-4 mb-5 mt-5 bg-body rounded">
        <div class="row">
            <h6>ЗАЛИШИТИ КОМЕНТАР : </h6>
            <div>
                {% comment %} <form action="{% url 'add_comments' recipe.id %}" class="comments" method="post"> {% endcomment %}
                <form action="{% url 'add_comments' recipe.id %}" class="comments" method="post">
                    {% csrf_token %}

                    {% comment %} <div class="login-item col-xl-3 col-lg-3 col-md-4 col-sm-12">  
                        <span name="name">{{ user.username }}</span>
                    </div> {% endcomment %}
    
                    <div class="form-floating mb-3">
                        <input class="form-control" placeholder="Leave your name here" id="floatingInput" name="name">
                        <label for="floatingInput">Ім'я</label>
                    </div>

                    {% comment %} <div class="col-4 mb-3">
                        <label for="exampleFormControlInput1" class="form-label">
                            <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="Email" name="email">
                        </label>
                    </div> {% endcomment %}
                    {% comment %} <div class="col-4 mb-3">
                        <label for="exampleFormControlTextarea1" class="form-label">
                            <textarea class="form-control" id="exampleFormControlTextarea1" rows="5" placeholder="Коментар" name="text_comments"></textarea>
                        </label>
                    </div> {% endcomment %}
                    <div class="form-floating mb-3">
                        <textarea class="form-control" placeholder="Leave a comment here" id="floatingTextarea" height="200" name="text_comments"></textarea>
                        <label for="floatingTextarea">Коментар</label>
                    </div>

                    <div>
                        <button type="submit" class="btn btn-outline-secondary">Відправка</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% else %}
    <div class="container shadow p-4 mb-5 mt-5 bg-body rounded">
        <div class="row">
            <h6>ЗАЛИШИТИ КОМЕНТАР МОЖУТЬ ЛИШЕ АВТОРИЗОВАНІ КОРИСТУВАЧІ </h6>
        </div>
    </div>
    {% endif %}

    <div class="container all-comments">
        <h6>КОМЕНТАРІ : </h6>
        {% for comment in recipe.comments_set.all %}
            <div class="view-comment">
                <b><i>{{comment.name}}</i></b>
                <p><span>{{comment.text_comments}}</span></p>
                <p><span><b>{{ comment.date_added }}</b></span></p>
            </div>
        {%endfor%}
    </div>
</div>

{% endblock content %}

my_apps/recipes_app/templates/soup_page.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div class="recipe-item">
    <div class="container shadow p-4 mb-5 mt-5 bg-body rounded">
        <h1>Супи </h1>
        <div class="row gy-3">
            {% for i in soup %}
            <div class="col-lg-3 col-md-4 col-sm-6 col-6">
                <div class="card h-100 mb-3">
                    <a href="{{i.id}}"><img src="{{i.img.url}}" class="card-img-top" alt="..."></a>
                    <div class="card-body">
                    <a href="{{i.id}}">
                        <h5 class="card-title">{{i.name}}</h5>
                    </a>                     
                    <p class="card-text">{{i.short_desc}}</p>
                    </div>
                </div> 
            </div>            
            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}

my_apps/users_app/templates/authenticate/login.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div class="container shadow p-4 mb-5 mt-5 bg-body rounded">
    <div class="login">
        <h1>Увійти: </h1>
        <div>
            <form action="" method="post">
                {% csrf_token %}
                <div class="login-field col-3 mb-3">
                    <label for="exampleFormControlInput1" class="form-label">
                        <input type="text" class="form-control" name="username">
                    </label>
                </div>
                <div class="login-field col-3 mb-3">
                    <label for="exampleFormControlInput1" class="form-label">
                        <input type="password" class="form-control" name='password'>
                    </label>
                    {% comment %} <a href="#" class="new-password">Забули пароль?</a>                      {% endcomment %}
                </div>
                <div>
                    <button type="submit" class="btn btn-outline-secondary">Підтвердити</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

my_apps/users_app/templates/authenticate/password-reset.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div class="container shadow p-4 mb-5 mt-5 bg-body rounded">
    <div class="login">
        <h1>Відновлення паролю: </h1>
        <div>
            <form action="" method="post">
                {% csrf_token %}
                <div class="login-field col-3 mb-3">
                    <p>Введіть адресу вашої електронної пошти</p>
                    <label for="exampleFormControlInput1" class="form-label">
                        <input type="text" class="form-control" name="username">
                    </label>
                </div>
                <div>
                    <button type="submit" class="btn btn-outline-secondary">Підтвердити</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

my_apps/users_app/templates/authenticate/register_user.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

{% if form.errors %}
<div class="container message">
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          Ви припустилися помилки!!!
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>   
  </div>
{% endif %}

<div class="container shadow p-4 mb-5 mt-5 bg-body rounded">
    <div class="registration">
        <h1>Реєстрація: </h1>
        <div>
            <form class="mt-3" action="{% url 'register_user' %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                {% comment %} <div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">
                        <input type="text" class="form-control" name="username">
                    </label>
                </div>
                <div class=" mb-3">
                    <label for="exampleFormControlInput1" class="form-label">
                        <input type="password" class="form-control" name='password'>
                    </label>                        
                </div> {% endcomment %}
                
                <div>
                    <button type="submit" class="btn btn-outline-secondary mt-3">Підтвердити</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content %}